name: ios_battery_indicator
description: "A Flutter widget that replicates the native iOS battery indicator, including support for iOS 27 style and automatic system battery monitoring."
version: 1.7.3
homepage: https://runoob-coder.github.io/ios_battery_indicator/
repository: https://github.com/runoob-coder/ios_battery_indicator
issue_tracker: https://github.com/runoob-coder/ios_battery_indicator/issues
documentation: https://github.com/runoob-coder/ios_battery_indicator
topics:
  - battery-indicator
  - cupertino
  - widget
  - ui
  - components

screenshots:
  - description: "ios_battery_indicator"
    path: screenshots/battery.png
  - description: "90% Charging"
    path: screenshots/3.png
  - description: "20% Discharging - Low Battery Warning"
    path: screenshots/4.png
  - description: "80% Charging - Show Battery Percentage"
    path: screenshots/1.png
  - description: "65% Discharging - Show Battery Percentage"
    path: screenshots/2.png

include:
  - pubspec.yaml
  - CHANGELOG.md
  - LICENSE
  - README.md
  - README_CN.md
  - analysis_options.yaml
  - fonts/
  - lib/
  - test/
  - example/lib/
  - screenshots/

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  battery_plus: ^7.1.0
  device_info_plus: ^13.2.0
  version: ^3.0.2
  cutout: ^1.0.2
  ios_system_sound: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  fonts:
    - family: SF Pro
      fonts:
        - asset: ./fonts/SF-Pro.ttf
